### Create
POST localhost:8080/article-type/publisher
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcwNDc3MDYsImlkIjo2NCwicm9sZSI6IlBVQkxJU0hFUiIsImV4cCI6MTcwNzEzNDEwNiwiaXNzIjoiS3VuVXpUZXN0In0.qXxpLjh5p9qgsD63jSyxtpdP25n0Mth39it4gX07MdnTJOo_y0ZkoDS5AnmtorNDxegv3QUGSNZo2TsNC0vRBg

{
  "articleId": "16309e9d-f7bb-4b09-8912-b21b4a761931",
  "typeId": 1
}