### Create
POST localhost:8080/article/moderator
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgxNTE3NTksImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODIzODE1OSwiaXNzIjoiS3VuVXpUZXN0In0.49Rsyp4kMoi0WnpK6tR1AljgXtpWqNQH8IeC0WNa0kbmDRWGf-P3BxELzbI3z7fxoD175RNYDdwxbfHhZs19iw

{
  "title": "Test 1",
  "description": "O`zbekiston vs Qatar o`yini",
  "content": "bugun O`zbekiston yeb quydi.Shu munosabat bila hammani tabrikliman",
  "regionId": 1,
  "categoryId": 1,
  "articleType": [1,2,3],
  "photoId": "bd2d33cb-2ff1-4942-96e8-657a030eb804"
}
### delete
DELETE localhost:8080/article/moderator/5425443c-dadb-4593-b310-0b962bb8ba36
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczOTg3MjMsImlkIjo2NCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzQ4NTEyMywiaXNzIjoiS3VuVXpUZXN0In0.s2ARpRtbICJiElwrRseiUvuU2VbDoyFaEpWxmSZP6MqkwmGoAwQ80gK7CHCpwgaegDZZmLRX0OZvs4TyaReQ0A


### update
PUT localhost:8080/article/moderator/a502171c-0656-4cd2-984a-8d63b6088eb0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczOTg3MjMsImlkIjo2NCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzQ4NTEyMywiaXNzIjoiS3VuVXpUZXN0In0.s2ARpRtbICJiElwrRseiUvuU2VbDoyFaEpWxmSZP6MqkwmGoAwQ80gK7CHCpwgaegDZZmLRX0OZvs4TyaReQ0A

{
  "title": "O`zbekistanda bugun",
  "description": "Obxavo ma`lumotlari jjfgdjbds",
  "content": "kgsdlsnuwqgyugyuasyusyugsa",
  "shared_count": 2,
  "photoId": "54baef48-81dd-46d3-bf2c-dc8fc10565ba",
  "regionId": 1,
  "categoryId": 1,
  "articleType": [1,2,3,4,5,6]
}

### change status
PUT localhost:8080/article/changeStatusById/1a303d92-310e-4757-af90-404c3223f307
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc1OTA2NDksImlkIjo2NCwicm9sZSI6IlBVQkxJU0hFUiIsImV4cCI6MTcwNzY3NzA0OSwiaXNzIjoiS3VuVXpUZXN0In0.PfQzWryQ-6idR-tbZ5xEodjp6vbMo0x5HshsW4-qFLEGxqwc7z93TfPkLQqs_eyFMdP5aCbCLZLDus9fMgFr6g

{
  "status": "PUBLISHED"
}


### get article by types limit 5
GET localhost:8080/article/getLast5ArticleByTypes/2?limit=2

### Get Last 8  Articles witch id not included in given list
POST localhost:8080/article/getLast8ArticlesIdNotInclude
Content-Type: application/json

["594d1096-a539-4853-a7d0-05ae1e92b9c1","ab64c4c1-912d-4fa2-942b-d157c7147993"]

### Get Last 4 Article By Types and except given article id.
POST localhost:8080/article/getLast4ArticleByTypes/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgxNjQxMjAsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODI1MDUyMCwiaXNzIjoiS3VuVXpUZXN0In0.WYoFa7AQdqEze_-2trfFwZSU0xJYuAeEUHi-oLEt7Cw99bCceSqzHKmMI9MvVllhPod_uFl6xoXKDouCzUOInA

["71003006-ed24-4a26-90c5-f96297600ff0","594d1096-a539-4853-a7d0-05ae1e92b9c1"]

### Get 4 most read article
GET localhost:8080/article/get4MostReadArticles

### Get Last 5 Article By Types And By RegionKey
GET localhost:8080/article/getLast5ArticleByTypesAndByRegionKey?typeId=1&regionId=1

### Get article by region key paging
GET localhost:8080/article/getArticleListByRegionKeyPagination/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgyNjkyOTgsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODM1NTY5OCwiaXNzIjoiS3VuVXpUZXN0In0.8v2hMKjyddku7cfChLXvbbTWwDzhNAkmeCHBnrlBSzPcC9OaAY7_Sp0va8QzsBaU3J_8hcNfLq53kPob_o56MQ

### increase view count
GET localhost:8080/article/increaseArticleViewCountByArticleId/71003006-ed24-4a26-90c5-f96297600ff0

### filter
POST localhost:8080/article/filter
Content-Type: application/json

{
  "id": "dc9b6c88-0cb3-41f8-8e99-f351355f4192"
}




