### Create
POST localhost:8080/article/moderator
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcwNDYwNDEsImlkIjo2NCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzEzMjQ0MSwiaXNzIjoiS3VuVXpUZXN0In0.axHrqBTsYNujhS4DIDfYUGGYW55NvUS7K23vFvWxc9YM5Ils-hahv3l0NWwAg38UF18QZ7VFCm7sP1BGgCEeQA

{
  "title": "Futbol",
  "description": "O`zbekiston vs Qatar o`yini",
  "content": "bugun O`zbekiston yeb quydi.Shu munosabat bila hammani tabrikliman",
  "regionId": 1,
  "categoryId": 1
}
### delete
DELETE localhost:8080/article/moderator/16309e9d-f7bb-4b09-8912-b21b4a761931
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcwNTk4ODAsImlkIjo2NCwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNzE0NjI4MCwiaXNzIjoiS3VuVXpUZXN0In0.hWD4vCiqek8Kw-0Eh7IJMBH2bBj4bxjJ2D9RFJ-D14avTjh2nf9VJ-GZ8Nw5Xki1r7jsh5MnF5ISoQK5rg-Pxg