### Create
POST localhost:8080/article_type
Content-Type: application/json


{
  "order_number": 1,
  "name_uz": "Asosiy",
  "name_ru": "Oсновной",
  "name_en": "Main"
}

### Update
PUT localhost:8080/article_type/1
Content-Type: application/json

{
  "order_number": 2,
  "name_uz": "Muharir",
  "name_ru": "Редактор",
  "name_en": "Editor"
}

### delete
GET localhost:8080/article_type/delete/1

### Pagination
GET localhost:8080/article_type/pagination?page=1&size=2

### Get by lan
GET localhost:8080/article_type/geByLan?lan=eng

### Test
GET localhost:8080/article_type/test/1?lan=rdd