### Login admin
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}

### registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ja`far",
  "surname": "Norboyev",
  "password": "1212",
  "email": "norobyev@icloud.com",
  "phone": "+998931733292"
}

### verifivation gmail
GET http://localhost:8080/auth/verification/email/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY2MTg0NTEsImlkIjoyNiwiZXhwIjoxNzA2NjIyMDUxLCJpc3MiOiJLdW5VelRlc3QifQ.oda0pXx0aGL1cmbpWTs_LzUwDz8NDw2dpgogoa2hlMXkZhmPrvsc5YD_ac1kOsEfvTtrKnzNWGNOcbXjQpF-4Q

### resent gmail
GET localhost:8080/auth/resent?email=ahrororzimurodov@icloud.com

### verifivation sms
GET localhost:8080/auth/verification/code/19697

### resent sms
GET localhost:8080/auth/resentPhone/+998934693533

