### create
POST localhost:8080/comment/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQxODIsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAwNTgyLCJpc3MiOiJLdW5VelRlc3QifQ.wEYc7HVkIXMJzsF6p6PXd3H15dnsX8VPgqHEVSOjBPtS-8kRPYcaEAnFACmFav5AzlwpV7kaRa5yqVjNT-BTtQ

{
  "content": "test  fbhbhjfsabbafs",
  "articleId": "ddd19677-cdd7-411d-81e4-69033425b3a7",
  "replyId": 3
}

### update
PUT localhost:8080/comment/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc3MTcwNTQsImlkIjo2NCwicm9sZSI6IlBVQkxJU0hFUiIsImV4cCI6MTcwNzgwMzQ1NCwiaXNzIjoiS3VuVXpUZXN0In0.CajTn4tcbldyH48USYaa6jRW4lSxB9RF3WMIcWX3pc_r2A30E_MARRi3KWCY29DEjlaSPN7iNERC35UOy_1vqg

{
  "content": "futbol rasvo  bo`ldi",
  "articleId": "ddd19677-cdd7-411d-81e4-69033425b3a7"
}

### delete
DELETE localhost:8080/comment/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc3MTcwNTQsImlkIjo2NCwicm9sZSI6IlBVQkxJU0hFUiIsImV4cCI6MTcwNzgwMzQ1NCwiaXNzIjoiS3VuVXpUZXN0In0.CajTn4tcbldyH48USYaa6jRW4lSxB9RF3WMIcWX3pc_r2A30E_MARRi3KWCY29DEjlaSPN7iNERC35UOy_1vqg

### Get list by article id
GET localhost:8080/comment/getCommitListByArticleId/ddd19677-cdd7-411d-81e4-69033425b3a7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc3MTcwNTQsImlkIjo2NCwicm9sZSI6IlBVQkxJU0hFUiIsImV4cCI6MTcwNzgwMzQ1NCwiaXNzIjoiS3VuVXpUZXN0In0.CajTn4tcbldyH48USYaa6jRW4lSxB9RF3WMIcWX3pc_r2A30E_MARRi3KWCY29DEjlaSPN7iNERC35UOy_1vqg

### pagaination
GET localhost:8080/comment/pagination
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQxODIsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAwNTgyLCJpc3MiOiJLdW5VelRlc3QifQ.wEYc7HVkIXMJzsF6p6PXd3H15dnsX8VPgqHEVSOjBPtS-8kRPYcaEAnFACmFav5AzlwpV7kaRa5yqVjNT-BTtQ

### filter
POST localhost:8080/comment/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQxODIsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAwNTgyLCJpc3MiOiJLdW5VelRlc3QifQ.wEYc7HVkIXMJzsF6p6PXd3H15dnsX8VPgqHEVSOjBPtS-8kRPYcaEAnFACmFav5AzlwpV7kaRa5yqVjNT-BTtQ

{
  "profileId": 62
}

### Get replied list
GET localhost:8080/comment/getRepliedList/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQxODIsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDAwNTgyLCJpc3MiOiJLdW5VelRlc3QifQ.wEYc7HVkIXMJzsF6p6PXd3H15dnsX8VPgqHEVSOjBPtS-8kRPYcaEAnFACmFav5AzlwpV7kaRa5yqVjNT-BTtQ

