### Create profile admin
POST localhost:8080/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MjcyNjcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MTM2NjcsImlzcyI6Ikt1blV6VGVzdCJ9.XiUUpJa_suJ7vta7QZJMDmXxpHvpZdZ8u0_D5JSNhenzLWQGpiLHxwWVSCnQ3-Cr4NQOnHjaDBh2wThoziP57g

{
  "name": "ZZZ",
  "surname": "ZZZ",
  "phone": "998992345678",
  "password": "1111",
  "email": "21kd22@icloud.com",
  "status": "ACTIVE",
  "role": "MODERATOR"
}

### Update profiel admin
PUT localhost:8080/profile/63
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY5ODk5NTYsImlkIjo2Miwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3MDc2MzU2LCJpc3MiOiJLdW5VelRlc3QifQ.2-xieo59TqPm_CpqcNWRARXDcVKusO0-ZVsuNlEg8g3cCvVGvj9sYA0cjrXfvE6wqlU4potRDY4FlD9xNJt0og

{
  "name": "Ahror",
  "surname": "Orzimurodov",
  "phone": "998912344444",
  "password": "8888",
  "email": "test@icloud.com",
  "status": "BLOCK",
  "role": "MODERATOR"
}
### Update profile any
PUT localhost:8080/profile/any/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MDY1NDEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTI5NDEsImlzcyI6Ikt1blV6VGVzdCJ9.1QCpjHFvzM6Zp-RfLUEVDl1zHzcx5J6bR9smsRYxadlrMYuw5qjkvO7CW6bF5-5QBaY8esQZw5yNjApp6_I6ng

{
  "name": "Joni",
  "surname": "Joniyev",
  "phone": "998332314554",
  "password": "0000",
  "email": "joni@icloud.com",
  "status": "ACTIVE",
  "role": "MODERATOR"
}

### Pagination
GET localhost:8080/profile/pagination?page=1&size=3
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MDY1NDEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTI5NDEsImlzcyI6Ikt1blV6VGVzdCJ9.1QCpjHFvzM6Zp-RfLUEVDl1zHzcx5J6bR9smsRYxadlrMYuw5qjkvO7CW6bF5-5QBaY8esQZw5yNjApp6_I6ng

### delete by id
DELETE localhost:8080/profile/2
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MDY1NDEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTI5NDEsImlzcyI6Ikt1blV6VGVzdCJ9.1QCpjHFvzM6Zp-RfLUEVDl1zHzcx5J6bR9smsRYxadlrMYuw5qjkvO7CW6bF5-5QBaY8esQZw5yNjApp6_I6ng

### filter
POST localhost:8080/profile/filter
Content-Type: application/json

{
  "surname": "ev"
}

### update role
PUT localhost:8080/profile/adm/updateRole/64
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY5OTIyOTcsImlkIjo2Miwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3MDc4Njk3LCJpc3MiOiJLdW5VelRlc3QifQ.IGzXYDnTxcPCJxTfFVyN2Jux60zCxW1BXvbFy8jocG8aJ5_Wu6T3ojzXuIn-hojluERtHyBX9HMEE6SYjhAZiw

{
  "role": "MODERATOR"
}
