### Create
POST localhost:8080/region/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MzgwNzYsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTI0NDc2LCJpc3MiOiJLdW5VelRlc3QifQ.0OBzgIu7W5dTSq-7U5d7vtKdkpqEhx7bEMyQGNMdD94NLMVRPqkb20v7nEqAOTn3Pxf9va1DfHdExZRwgsWH_w

{
  "order_number": 10,
  "nameUz": "Buxoro uz",
  "nameEn": "Buxoro eng",
  "nameRu": "Buxoro ru"
}

### Update
PUT localhost:8080/region/adm/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MjA1NjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MDY5NjYsImlzcyI6Ikt1blV6VGVzdCJ9.jLFKaIoTtMDowL7byfUTtO6533bmJ0UEdEOrSFjYRF--grct7MQbFNqVEuaEr0S2zYvtiuT3bV0Vv9tV5F1gzQ



{
  "order_number": 2,
  "nameUz": "O`zbekiston",
  "nameRu": "Узбекистон",
  "nameEn": "Uzbekistan"
}

### Delete
DELETE localhost:8080/region/adm/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MjA1NjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MDY5NjYsImlzcyI6Ikt1blV6VGVzdCJ9.jLFKaIoTtMDowL7byfUTtO6533bmJ0UEdEOrSFjYRF--grct7MQbFNqVEuaEr0S2zYvtiuT3bV0Vv9tV5F1gzQ"


### Get all
GET localhost:8080/region/adm
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MjA1NjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MDY5NjYsImlzcyI6Ikt1blV6VGVzdCJ9.jLFKaIoTtMDowL7byfUTtO6533bmJ0UEdEOrSFjYRF--grct7MQbFNqVEuaEr0S2zYvtiuT3bV0Vv9tV5F1gzQ"


### Get by lan
GET localhost:8080/region/geByLan?lan=ru
