### Create
POST localhost:8080/saved-article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgzNDUwNTgsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODQzMTQ1OCwiaXNzIjoiS3VuVXpUZXN0In0.U1CjcbagYRBIOFiyqZqIRpS8I9QObpagQ66Q_zsDpRMIheXgyM4sUuRWf2LPHaDvQlPz1GM2yAqM1xBS-CAV6w

{
  "articleId": "dc9b6c88-0cb3-41f8-8e99-f351355f4192"
}

### delete
DELETE localhost:8080/saved-article/dc9b6c88-0cb3-41f8-8e99-f351355f4192
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgzNDUwNTgsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODQzMTQ1OCwiaXNzIjoiS3VuVXpUZXN0In0.U1CjcbagYRBIOFiyqZqIRpS8I9QObpagQ66Q_zsDpRMIheXgyM4sUuRWf2LPHaDvQlPz1GM2yAqM1xBS-CAV6w

### Get all
GET localhost:8080/saved-article
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgzNDUwNTgsImVtYWlsIjoiYWRtaW5jZWVrQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX01PREVSQVRPUiIsImV4cCI6MTcwODQzMTQ1OCwiaXNzIjoiS3VuVXpUZXN0In0.U1CjcbagYRBIOFiyqZqIRpS8I9QObpagQ66Q_zsDpRMIheXgyM4sUuRWf2LPHaDvQlPz1GM2yAqM1xBS-CAV6w

