### Create
POST localhost:8080/type/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgxNTE0NTksImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MjM3ODU5LCJpc3MiOiJLdW5VelRlc3QifQ.DrFaD0G4q3peO8woq_aPpAzraNYbhBJkE70z5scLjrnOoPTdSZG07muTHG2gfEi9vez6Ph5Gd1tBxPjjmyPdOQ

{
  "order_number": 9,
  "nameUz": "test3 uz",
  "nameRu": "test3 ru",
  "nameEn": "test3 eng"
}

### Update
PUT localhost:8080/type/1
Content-Type: application/json

{
  "order_number": 2,
  "name_uz": "Muharir",
  "name_ru": "Редактор",
  "name_en": "Editor"
}

### delete
GET localhost:8080/type/delete/1

### Pagination
GET localhost:8080/type/pagination?page=1&size=2

### Get by lan
GET localhost:8080/type/geByLan?lan=eng

### Test
GET localhost:8080/type/test/1?lan=rdd